### ISSUE TITLE
linux command line not work

### ISSUE THREAD

**Issue by dipenpatel235** [Nexuist/PDF-2-DOC-Utility#1]
hello..
i have installed all and trying using below command but getting DISPLAY error.
i am using virtual server so i have not displayed.
so any solution convert it without display ?
 
python main.py my.pdf

_tkinter.TclError: no display name and no $DISPLAY environment variable

Thanks

**Comment by Nexuist** [comment]
Hi,

I wasn't anticipating command line usage when developing this app. Instead of using a server, could you just use your personal computer? Python runs on all three major platforms, you probably have one of them.

**Comment by dipenpatel235** [comment]
no i have not personal computer.
i have linux cloud server and my goal is using api i want to convert pdf to doc.

thanks

**Comment by ProxyAi** [comment]
Im getting the same issue

ive installed the requests-toolbelt & pip install requests
root@108:/home# python --version
Python 2.7.13

![image](https://user-images.githubusercontent.com/11992984/34942059-20540c1c-f9ee-11e7-9d8e-dad2cf836519.png)

**Comment by FirdousBhat** [comment]
![image](https://user-images.githubusercontent.com/22815856/52326244-fe3f1800-2a0d-11e9-882f-90987c97e95d.png)
I'm getting that error

**Comment by Nexuist** [comment]
@FirdousBhat Hi, try installing Tkinter: [https://stackoverflow.com/questions/4783810/install-tkinter-for-python](https://stackoverflow.com/questions/4783810/install-tkinter-for-python)
