### ISSUE TITLE
Does the project have no open source core conversion pdf source code .

### ISSUE THREAD

**Issue by LockGit** [Nexuist/PDF-2-DOC-Utility#2]
View the source code ， The project have no open source core conversion pdf source code ...

**Comment by Nexuist** [comment]
It does not. It uses http://pdf2doc.com/

**Comment by LockGit** [comment]
This is not an open source project

**Comment by Nexuist** [comment]
The source of the application is available within the repo.

**Comment by wlevene** [comment]
pdf2document.com - No loss of pdf layout
30 free page conversions daily for all users.
